### ISSUE TITLE
能否贴出源码，或大致描述实现原理

### ISSUE THREAD

**Issue by ghost** [yltx/Space-Deleter#1]
如题
我也写过一个用正则表达式实现的代码压行+删注释+删缩进&多余空格的玩意，也许能有点用，但不了解作者这个程序的实现原理，故无法确定。

**Comment by yltx** [comment]
> 如题
> 我也写过一个用正则表达式实现的代码压行+删注释+删缩进&多余空格的玩意，也许能有点用，但不了解作者这个程序的实现原理，故无法确定。

qwq

根据C++常用语法写的，一般的字母和特殊字符之间是不需要空格的

**Comment by yltx** [comment]
> 如题
> 我也写过一个用正则表达式实现的代码压行+删注释+删缩进&多余空格的玩意，也许能有点用，但不了解作者这个程序的实现原理，故无法确定。

删之前最新的版本，自己看吧 https://github.com/yltx/Space-Deleter/blob/c5372be50ef885961685465a8e630cdddc8b7dbe/Space-Deleter-master.cpp
