### ISSUE TITLE
32位机器运行不了

### ISSUE THREAD

**Issue by szdytom** [yltx/Space-Deleter#2]
32位机器运行不了
![pic1](https://user-images.githubusercontent.com/33175397/61685074-130a3080-ad4e-11e9-9803-253a4ee172e0.PNG)

**Comment by yltx** [comment]
> 32位机器运行不了
> ![pic1](https://user-images.githubusercontent.com/33175397/61685074-130a3080-ad4e-11e9-9803-253a4ee172e0.PNG)

了解了，下一次发布会分别发布64位和32位的exe

**Comment by yltx** [comment]
fixed
