### ISSUE TITLE
部分空格无法删除

### ISSUE THREAD

**Issue by VictoryDefeat** [yltx/Space-Deleter#3]
经过测试，`using namespace  std;`中的空格无法删除且空行会显示奇怪符号

**Comment by yltx** [comment]
> 经过测试，`using namespace std;`中的空格无法删除且空行会显示奇怪符号

您说的是什么意思？？？

我为了避免有时候CE或者把一些不该删的空格删了，有的部分还没有写好。至于空行会显示奇怪符号的问题，麻烦截个图QAQ

**Comment by VictoryDefeat** [comment]
额，是using namespace    std;（万恶的Markdown没显示出来，namespace与std之间有多个空格），图：![](https://cdn.luogu.org/upload/pic/75329.png)（第9行那个，打开时提示此文件是二进制文件，编译器VSCode）

**Comment by VictoryDefeat** [comment]
Github的Markdown有毒吧……

**Comment by yltx** [comment]
> Github的Markdown有毒吧……

奥，这个两个空格我是直接自动识别为缩进的，是个锅，会修的

关于空行未知字符的问题，严重怀疑您是在DevC++中编辑，然后在VSC中打开，这两个编辑器编码不一样，连输入中文都很容易乱码，麻烦您好好检查一下您的原代码

**Comment by VictoryDefeat** [comment]
> > Github的Markdown有毒吧……
> 
> 奥，这个两个空格我是直接自动识别为缩进的，是个锅，会修的
> 
> 关于空行未知字符的问题，严重怀疑您是在DevC++中编辑，然后在VSC中打开，这两个编辑器编码不一样，连输入中文都很容易乱码，麻烦您好好检查一下您的原代码

然而，我是全程在VSCode中编辑的，过程中并未使用其它编辑器

**Comment by yltx** [comment]
> > > Github的Markdown有毒吧……
> > 
> > 
> > 奥，这个两个空格我是直接自动识别为缩进的，是个锅，会修的
> > 关于空行未知字符的问题，严重怀疑您是在DevC++中编辑，然后在VSC中打开，这两个编辑器编码不一样，连输入中文都很容易乱码，麻烦您好好检查一下您的原代码
> 
> 然而，我是全程在VSCode中编辑的，过程中并未使用其它编辑器

行吧。您原代码用代码框给一下？

**Comment by yltx** [comment]
fixed
